baseURL = "https://net-admin.pro/"
languageCode = "ru-RU"
title = "Office-Admin — IT-услуги для офисов"
theme = "ananke"   # можно любой минималистичный, поддерживающий адаптив
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
